# Generated by Django 5.1.7 on 2025-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_price_alter_item_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock_quantity',
            new_name='stockQuantity',
        ),
    ]
