# Generated by Django 5.1.7 on 2025-05-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_stock_quantity_item_stockquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='type',
        ),
    ]
