# Generated by Django 5.1.7 on 2025-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_item_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
