# Generated by Django 5.1.7 on 2025-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_remove_item_is_deleted_item_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
