# Generated by Django 5.1.7 on 2025-05-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='limit',
            field=models.IntegerField(default=10),
        ),
    ]
