# Generated by Django 5.1.7 on 2025-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_item_buyprice_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
