# Generated by Django 5.1.7 on 2025-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_item_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isActive',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='isActive',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='item_item_name_a28963_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['type'], name='item_item_type_81d9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['isActive'], name='item_item_isActiv_801510_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['item'], name='item_source_item_id_26e1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['isActive'], name='item_source_isActiv_3cefd0_idx'),
        ),
    ]
