# Generated by Django 5.1.7 on 2025-05-21 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_item_isactive_alter_item_name_alter_item_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buyPrice',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
