# Generated by Django 5.2.3 on 2025-06-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_item_buyprice_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tva',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
