# Generated by Django 5.2.3 on 2025-07-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_item_tva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stockQuantity',
            new_name='stock_quantity',
        ),
    ]
