# Generated by Django 5.2.3 on 2025-07-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_rename_stockquantity_item_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock_quantity',
            new_name='stockQuantity',
        ),
    ]
