# Generated by Django 5.2.3 on 2025-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_rename_stock_quantity_item_stockquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stockQuantity',
            field=models.IntegerField(default=0),
        ),
    ]
