# Generated by Django 5.1.7 on 2025-04-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_address_landline_alter_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='addresses'),
        ),
    ]
