# Generated by Django 5.1.7 on 2025-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_address_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landline',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
