# Generated by Django 5.1.7 on 2025-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landline',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
