# Generated by Django 5.1.7 on 2025-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_address_landline_alter_address_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('firstName', 'lastName')},
        ),
    ]
