# Generated by Django 5.1.7 on 2025-05-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_first_name_customer_firstname_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='address',
            name='mobile',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='address',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='middleName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='nickName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='addresses'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('firstName', 'middleName', 'lastName')},
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=40)),
                ('priority', models.IntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_numbers', to='customer.address')),
            ],
        ),
    ]
