# Generated by Django 5.1.7 on 2025-05-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_unique_together_remove_address_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='middleName',
            field=models.CharField(max_length=50),
        ),
    ]
