# Generated by Django 5.1.7 on 2025-05-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(max_length=70),
        ),
    ]
