# Generated by Django 5.1.7 on 2025-05-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='residence_ehden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='residence_zgharta',
            field=models.BooleanField(default=False),
        ),
    ]
