# Generated by Django 5.1.7 on 2025-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_rename_residence_ehden_customer_residenceehden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='customer',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
