# Generated by Django 5.1.7 on 2025-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_remove_address_text_address_building_address_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='residenceKoura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='residenceTripoli',
            field=models.BooleanField(default=False),
        ),
    ]
