# Generated by Django 5.1.7 on 2025-05-21 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_customer_firstname_alter_customer_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='address',
            name='landline',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='mobile',
            field=models.CharField(db_index=True, default='', max_length=40, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number in E.164 format (e.g., +12345678901).', regex='^\\+[1-9]\\d{6,14}$')]),
        ),
    ]
