# Generated by Django 5.2.3 on 2025-07-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_address_email_alter_address_landline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
