# Generated by Django 5.2.3 on 2025-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_address_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='link',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
