# Generated by Django 5.2.3 on 2025-07-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_address_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='notes',
            field=models.TextField(default='', null=True),
        ),
    ]
