# Generated by Django 5.2.3 on 2025-07-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_address_building_alter_address_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
