# Generated by Django 5.2.3 on 2025-07-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
