# Generated by Django 5.2.3 on 2025-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='middleName',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
    ]
