# Generated by Django 5.2.3 on 2025-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_customer_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='middleName',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, null=True),
        ),
    ]
