# Generated by Django 5.1.7 on 2025-04-30 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+ 999999999'. Up to 20 digits allowed.", regex='^\\+?1?\\d{9,20}$')]),
        ),
    ]
