# Generated by Django 5.1.7 on 2025-05-01 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 20 digits allowed.", regex='^\\d{9,20}$')]),
        ),
    ]
