# Generated by Django 5.1.7 on 2025-05-13 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid international phone number in E.164 format (e.g., +12345678901).', regex='^\\+[1-9]\\d{6,14}$')]),
        ),
    ]
