# Generated by Django 5.2.3 on 2025-09-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
