# Generated by Django 5.1.7 on 2025-04-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.FloatField(default=0)),
                ('status', models.CharField(default='P', max_length=1)),
                ('customer_notes', models.TextField()),
                ('driver_notes', models.TextField()),
                ('lira_rate', models.IntegerField()),
                ('orderedAt', models.DateTimeField(auto_now_add=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='item.item')),
            ],
        ),
    ]
