# Generated by Django 5.1.7 on 2025-04-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_customer_notes_alter_order_driver_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
