# Generated by Django 5.1.7 on 2025-05-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_customer_notes_alter_order_driver_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_notes',
            new_name='customerNotes',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='driver_notes',
            new_name='driverNotes',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lira_rate',
            new_name='liraRate',
        ),
    ]
