# Generated by Django 5.1.7 on 2025-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_is_deleted_order_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts')),
                ('orders', models.ManyToManyField(to='order.order')),
            ],
        ),
    ]
