# Generated by Django 5.1.7 on 2025-05-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
