# Generated by Django 5.1.7 on 2025-05-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isActive',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.CharField(choices=[('USD', 'USD'), ('LBP', 'LBP')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderedAt',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
